import { useCallback, useEffect, useState } from "react";
import { CheckCircle2, CircleAlert, ExternalLink, RefreshCw, ShieldCheck, Wrench, X } from "lucide-react";

type Gap={finding_id:number;resource_name:string;policy_name:string;severity:string;remediation_status:string;recommendation:string};
type Control={code:string;title:string;domain:string;status:"passed"|"failed"|"accepted"|"not_assessed";mapped_policies:number;evidence_count:number;gaps:Gap[]};
type Framework={slug:string;name:string;version:string;description:string;source_url:string;readiness_percent:number;passed:number;failed:number;accepted:number;not_assessed:number;controls:Control[]};
type Readiness={disclaimer:string;frameworks:Framework[]};

export default function CompliancePage({token,onManageFindings}:{token:string;onManageFindings:()=>void}){
  const api=import.meta.env.VITE_API_URL??"/api";
  const [data,setData]=useState<Readiness|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
  const [selected,setSelected]=useState<Control|null>(null);
  const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await fetch(`${api}/compliance/readiness`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)throw new Error("Compliance readiness could not be loaded.");setData(await response.json());}catch(reason){setError(reason instanceof Error?reason.message:"Compliance readiness could not be loaded.");}finally{setLoading(false)}},[api,token]);
  useEffect(()=>{void load()},[load]);
  if(loading)return <div className="resource-state compliance-state"><RefreshCw className="spinning"/><strong>Connecting framework evidence…</strong></div>;
  if(error||!data)return <div className="resource-error">{error||"Compliance readiness is unavailable."}</div>;
  return <><section className="page-heading"><div><span className="eyebrow accent">Evidence-based assurance</span><h1>Compliance readiness</h1><p>Translate verified cloud configuration evidence into an honest, traceable framework view.</p></div><button className="refresh-button" onClick={()=>void load()}><RefreshCw/> Refresh evidence</button></section>
    <div className="compliance-disclaimer"><ShieldCheck/><span>{data.disclaimer}</span></div>
    <section className="framework-grid">{data.frameworks.map(framework=><article className="panel framework-card" key={framework.slug}><header><div><span className="eyebrow">{framework.version}</span><h2>{framework.name}</h2><p>{framework.description}</p></div><div className="readiness-ring" style={{"--readiness":`${framework.readiness_percent*3.6}deg`} as React.CSSProperties}><strong>{framework.readiness_percent}%</strong></div></header><div className="framework-summary"><span><b>{framework.passed}</b> Passed</span><span><b>{framework.failed}</b> Gaps</span><span><b>{framework.not_assessed}</b> Not assessed</span></div><div className="control-list">{framework.controls.map(control=><button type="button" onClick={()=>control.gaps.length&&setSelected(control)} key={control.code}><span className={`control-status ${control.status}`}>{control.status==="passed"?<CheckCircle2/>:<CircleAlert/>}</span><div><strong>{control.code} · {control.title}</strong><small>{control.domain} · {control.evidence_count} evidence result{control.evidence_count===1?"":"s"}</small></div><em className={control.status}>{control.status.replace("_"," ")}</em>{control.gaps.length>0&&<Wrench className="control-action"/>}</button>)}</div><a href={framework.source_url} target="_blank" rel="noreferrer">Official framework source <ExternalLink/></a></article>)}</section>
    {selected&&<div className="modal-backdrop"><section className="resource-modal guidance-modal" role="dialog" aria-modal="true"><div className="modal-heading"><div><span className="eyebrow accent">Guided remediation</span><h2>{selected.code} · {selected.title}</h2><p>{selected.gaps.length} evidence-backed gap{selected.gaps.length===1?"":"s"} require action.</p></div><button className="icon-button" onClick={()=>setSelected(null)}><X/></button></div><div className="playbook-steps"><span><b>1</b>Apply the recommended cloud configuration change.</span><span><b>2</b>Manage ownership, due date, and evidence in Findings.</span><span><b>3</b>Run a new scan; only verified passing evidence raises readiness.</span></div><div className="guidance-list">{selected.gaps.map(gap=><article key={gap.finding_id}><div><span className={`severity ${gap.severity}`}>{gap.severity}</span><em>{gap.remediation_status.replace("_"," ")}</em></div><h3>{gap.resource_name}</h3><p>{gap.recommendation}</p><small>{gap.policy_name} · Finding #{gap.finding_id}</small></article>)}</div><div className="modal-actions"><button onClick={()=>setSelected(null)}>Close</button><button className="primary-button" onClick={onManageFindings}><Wrench/>Manage in Findings</button></div></section></div>}
  </>;
}
