import { FormEvent, useCallback, useEffect, useState } from "react";
import { CheckCircle2, FlaskConical, Plus, RefreshCw, ScrollText, ShieldAlert, X, XCircle } from "lucide-react";

type Provider = "aws" | "azure" | "gcp";
type Severity = "low" | "medium" | "high" | "critical";
type RuleType = "boolean_property_equals" | "field_must_exist";
type Policy = { id:number; name:string; description:string; severity:Severity; cloud_provider:Provider; resource_type:string; rule_type:RuleType; rule_config:Record<string,unknown>; is_active:boolean; created_at:string };
type EvaluationResult = { policy_id:number; policy_name:string; severity:string; compliant:boolean; details:string };
type Evaluation = { resource_name:string; checked_policy_count:number; results:EvaluationResult[] };

const blankPolicy = { name:"", description:"", severity:"medium" as Severity, cloud_provider:"aws" as Provider, resource_type:"s3_bucket", rule_type:"boolean_property_equals" as RuleType, field:"encryption_enabled", expectedValue:true };
const blankEvaluation = { resource_name:"Portfolio Audit Bucket", cloud_provider:"aws" as Provider, resource_type:"s3_bucket", configuration:'{"public_access_blocked": true, "encryption_enabled": true}' };

export default function PoliciesPage({token}:{token:string}) {
  const [policies,setPolicies]=useState<Policy[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const [includeInactive,setIncludeInactive]=useState(false); const [showCreate,setShowCreate]=useState(false); const [showEvaluate,setShowEvaluate]=useState(false);
  const [form,setForm]=useState(blankPolicy); const [evaluationForm,setEvaluationForm]=useState(blankEvaluation); const [evaluation,setEvaluation]=useState<Evaluation|null>(null); const [saving,setSaving]=useState(false);
  const apiBase=import.meta.env.VITE_API_URL??"/api";

  const loadPolicies=useCallback(async()=>{setLoading(true);setError("");try{const response=await fetch(`${apiBase}/policies?include_inactive=${includeInactive}`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)throw new Error(await readError(response));setPolicies(await response.json());}catch(reason){setError(reason instanceof Error?reason.message:"Policies could not be loaded.");}finally{setLoading(false);}},[apiBase,includeInactive,token]);
  useEffect(()=>{void loadPolicies();},[loadPolicies]);

  async function createPolicy(event:FormEvent){event.preventDefault();setSaving(true);setError("");try{const rule_config:Record<string,unknown>={field:form.field};if(form.rule_type==="boolean_property_equals")rule_config.expected_value=form.expectedValue;const response=await fetch(`${apiBase}/policies`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({...form,rule_config})});if(!response.ok)throw new Error(await readError(response));setForm(blankPolicy);setShowCreate(false);await loadPolicies();}catch(reason){setError(reason instanceof Error?reason.message:"Policy could not be created.");}finally{setSaving(false);}}

  async function evaluate(event:FormEvent){event.preventDefault();setSaving(true);setError("");try{let configuration:Record<string,unknown>;try{configuration=JSON.parse(evaluationForm.configuration);}catch{throw new Error("Configuration must be valid JSON.");}const response=await fetch(`${apiBase}/policies/evaluate`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({...evaluationForm,configuration})});if(!response.ok)throw new Error(await readError(response));setEvaluation(await response.json());}catch(reason){setError(reason instanceof Error?reason.message:"Evaluation failed.");}finally{setSaving(false);}}

  return <>
    <section className="page-heading"><div><span className="eyebrow accent">Deterministic controls</span><h1>Policies</h1><p>Create security rules and evaluate cloud configurations with explainable results.</p></div><div className="heading-actions"><button className="secondary-button" onClick={()=>{setEvaluation(null);setShowEvaluate(true);}}><FlaskConical/> Test configuration</button><button className="primary-button" onClick={()=>setShowCreate(true)}><Plus/> Add policy</button></div></section>
    <section className="policy-summary"><div><span><ScrollText/></span><strong>{policies.length}</strong><small>Visible policies</small></div>{(["critical","high","medium","low"] as Severity[]).map(severity=><div key={severity}><span className={`severity-icon ${severity}`}><ShieldAlert/></span><strong>{policies.filter(policy=>policy.severity===severity).length}</strong><small>{severity} severity</small></div>)}</section>
    <section className="panel policy-panel"><div className="policy-toolbar"><div><h2>Policy library</h2><p>Controls currently available to the rule engine</p></div><label className="inactive-toggle"><input type="checkbox" checked={includeInactive} onChange={event=>setIncludeInactive(event.target.checked)}/> Include inactive</label><button className="refresh-button" onClick={()=>void loadPolicies()}><RefreshCw/> Refresh</button></div>{error&&<div className="resource-error">{error}</div>}{loading?<div className="resource-state"><RefreshCw className="spinning"/><strong>Loading policies…</strong></div>:policies.length===0?<div className="resource-state"><ScrollText/><strong>No policies found</strong><p>Create the first deterministic security control.</p><button className="text-button" onClick={()=>setShowCreate(true)}>Add a policy →</button></div>:<div className="policy-grid">{policies.map(policy=><article className="policy-card" key={policy.id}><div className="policy-card-top"><span className={`severity-icon ${policy.severity}`}><ShieldAlert/></span><div><span className={`severity ${policy.severity}`}>{policy.severity}</span><span className={`status-pill ${policy.is_active?"active":"inactive"}`}>{policy.is_active?"active":"inactive"}</span></div></div><h3>{policy.name}</h3><p>{policy.description}</p><div className="policy-meta"><span>{policy.cloud_provider.toUpperCase()}</span><span>{policy.resource_type}</span></div><div className="rule-box"><small>{policy.rule_type.replaceAll("_"," ")}</small><code>{String(policy.rule_config.field)}{policy.rule_type==="boolean_property_equals"?` = ${String(policy.rule_config.expected_value)}`:" must exist"}</code></div></article>)}</div>}</section>

    {showCreate&&<div className="modal-backdrop"><section className="resource-modal"><ModalHeading eyebrow="Security control" title="Create policy" text="Define an explainable rule for matching cloud resources." close={()=>setShowCreate(false)}/><form onSubmit={createPolicy}><div className="form-grid"><label>Policy name<input required minLength={3} maxLength={120} value={form.name} onChange={event=>setForm({...form,name:event.target.value})} placeholder="S3 encryption required"/></label><label>Severity<select value={form.severity} onChange={event=>setForm({...form,severity:event.target.value as Severity})}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select></label><label>Cloud provider<select value={form.cloud_provider} onChange={event=>setForm({...form,cloud_provider:event.target.value as Provider})}><option value="aws">AWS</option><option value="azure">Azure</option><option value="gcp">Google Cloud</option></select></label><label>Resource type<input required minLength={3} maxLength={100} value={form.resource_type} onChange={event=>setForm({...form,resource_type:event.target.value})}/></label><label>Rule type<select value={form.rule_type} onChange={event=>setForm({...form,rule_type:event.target.value as RuleType})}><option value="boolean_property_equals">Boolean property equals</option><option value="field_must_exist">Field must exist</option></select></label><label>Configuration field<input required value={form.field} onChange={event=>setForm({...form,field:event.target.value})}/></label></div><label>Description<textarea required minLength={10} maxLength={1000} rows={3} value={form.description} onChange={event=>setForm({...form,description:event.target.value})} placeholder="Ensure all S3 buckets have server-side encryption enabled."/></label>{form.rule_type==="boolean_property_equals"&&<label className="expected-toggle">Expected value<select value={String(form.expectedValue)} onChange={event=>setForm({...form,expectedValue:event.target.value==="true"})}><option value="true">True</option><option value="false">False</option></select></label>}<ModalActions cancel={()=>setShowCreate(false)} saving={saving} label="Create policy"/></form></section></div>}

    {showEvaluate&&<div className="modal-backdrop"><section className="resource-modal evaluation-modal"><ModalHeading eyebrow="Rule engine" title="Test configuration" text="Run matching active policies without starting a background scan." close={()=>setShowEvaluate(false)}/><form onSubmit={evaluate}><div className="form-grid"><label>Resource name<input required value={evaluationForm.resource_name} onChange={event=>setEvaluationForm({...evaluationForm,resource_name:event.target.value})}/></label><label>Resource type<input required minLength={3} value={evaluationForm.resource_type} onChange={event=>setEvaluationForm({...evaluationForm,resource_type:event.target.value})}/></label><label>Cloud provider<select value={evaluationForm.cloud_provider} onChange={event=>setEvaluationForm({...evaluationForm,cloud_provider:event.target.value as Provider})}><option value="aws">AWS</option><option value="azure">Azure</option><option value="gcp">Google Cloud</option></select></label></div><label>Configuration JSON<textarea required rows={6} value={evaluationForm.configuration} onChange={event=>setEvaluationForm({...evaluationForm,configuration:event.target.value})}/></label><button className="primary-button evaluation-button" disabled={saving}>{saving?"Evaluating…":"Run evaluation"}</button></form>{evaluation&&<div className="evaluation-results"><div><strong>{evaluation.checked_policy_count}</strong><span>matching policies checked</span></div>{evaluation.results.length===0?<p>No active policies match this provider and resource type.</p>:evaluation.results.map(result=><article className={result.compliant?"compliant":"noncompliant"} key={result.policy_id}>{result.compliant?<CheckCircle2/>:<XCircle/>}<div><strong>{result.policy_name}</strong><span>{result.details}</span></div><em>{result.compliant?"Compliant":"Action required"}</em></article>)}</div>}</section></div>}
  </>;
}

function ModalHeading({eyebrow,title,text,close}:{eyebrow:string;title:string;text:string;close:()=>void}){return <div className="modal-heading"><div><span className="eyebrow accent">{eyebrow}</span><h2>{title}</h2><p>{text}</p></div><button className="icon-button" onClick={close}><X/></button></div>}
function ModalActions({cancel,saving,label}:{cancel:()=>void;saving:boolean;label:string}){return <div className="modal-actions"><button type="button" onClick={cancel}>Cancel</button><button className="primary-button" disabled={saving}>{saving?"Saving…":label}</button></div>}
async function readError(response:Response){try{const body=await response.json();if(typeof body.detail==="string")return body.detail;if(Array.isArray(body.detail))return body.detail[0]?.msg??"Please check the policy details.";}catch{return "The service returned an unexpected response.";}return "The request failed.";}
