import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, Download, FileBarChart, RefreshCw, ShieldCheck } from "lucide-react";

type Provider="aws"|"azure"|"gcp";
type Scan={id:number;cloud_provider:Provider;status:string;total_resources:number;compliant_count:number;non_compliant_count:number;created_at:string};
type Result={id:number;scan_id:number;resource_id:number;policy_id:number;compliant:boolean;details:string;created_at:string};
type Resource={id:number;name:string;cloud_provider:Provider;resource_type:string};
type Policy={id:number;name:string;severity:string};
type Finding=Result&{resource?:Resource;policy?:Policy};

export default function ReportsPage({token}:{token:string}){
  const apiBase=import.meta.env.VITE_API_URL??"/api"; const headers={Authorization:`Bearer ${token}`};
  const [scans,setScans]=useState<Scan[]>([]); const [resources,setResources]=useState<Resource[]>([]); const [policies,setPolicies]=useState<Policy[]>([]); const [results,setResults]=useState<Result[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{const [scanResponse,resourceResponse,policyResponse]=await Promise.all([fetch(`${apiBase}/scans`,{headers}),fetch(`${apiBase}/resources?include_inactive=true`,{headers}),fetch(`${apiBase}/policies?include_inactive=true`,{headers})]);if(!scanResponse.ok||!resourceResponse.ok||!policyResponse.ok)throw new Error("Report data could not be loaded.");const scanData:Scan[]=await scanResponse.json();const resourceData:Resource[]=await resourceResponse.json();const policyData:Policy[]=await policyResponse.json();const completed=scanData.filter(scan=>scan.status==="completed");const groups=await Promise.all(completed.map(async scan=>{const response=await fetch(`${apiBase}/scans/${scan.id}/results`,{headers});return response.ok?await response.json() as Result[]:[];}));setScans(scanData);setResources(resourceData);setPolicies(policyData);setResults(groups.flat());}catch(reason){setError(reason instanceof Error?reason.message:"Report data could not be loaded.");}finally{setLoading(false);}},[apiBase,token]);
  useEffect(()=>{void load();},[load]);
  const resourceMap=useMemo(()=>new Map(resources.map(item=>[item.id,item])),[resources]); const policyMap=useMemo(()=>new Map(policies.map(item=>[item.id,item])),[policies]);
  const findings=useMemo<Finding[]>(()=>results.filter(item=>!item.compliant).map(item=>({...item,resource:resourceMap.get(item.resource_id),policy:policyMap.get(item.policy_id)})),[results,resourceMap,policyMap]);
  const completed=scans.filter(scan=>scan.status==="completed"); const passed=results.filter(item=>item.compliant).length; const rate=results.length?Math.round(passed/results.length*100):0;
  const providers=(["aws","azure","gcp"] as Provider[]).map(provider=>({provider,resources:resources.filter(item=>item.cloud_provider===provider).length,findings:findings.filter(item=>item.resource?.cloud_provider===provider).length}));
  function exportCsv(){const rows=[["Scan","Provider","Resource","Type","Policy","Severity","Result","Details"],...findings.map(item=>[String(item.scan_id),item.resource?.cloud_provider.toUpperCase()??"Unknown",item.resource?.name??String(item.resource_id),item.resource?.resource_type??"Unknown",item.policy?.name??String(item.policy_id),item.policy?.severity??"Unknown","Non-compliant",item.details])];const csv=rows.map(row=>row.map(value=>`"${value.replaceAll('"','""')}"`).join(",")).join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download=`cloud-policy-report-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(url);}
  return <><section className="page-heading"><div><span className="eyebrow accent">Audit evidence</span><h1>Reports</h1><p>Summarise stored inventory and compliance evidence from completed scans.</p></div><div className="report-actions"><button className="refresh-button" onClick={()=>void load()}><RefreshCw/> Refresh</button><button className="primary-button" onClick={exportCsv} disabled={!findings.length}><Download/> Export CSV</button></div></section>{error&&<div className="resource-error">{error}</div>}{loading?<div className="resource-state"><RefreshCw className="spinning"/><strong>Building report…</strong></div>:<><section className="scan-summary report-summary"><Summary icon={ShieldCheck} value={`${rate}%`} label="Control pass rate" tone="cyan"/><Summary icon={FileBarChart} value={completed.length} label="Completed scans" tone="blue"/><Summary icon={CheckCircle2} value={passed} label="Passed controls" tone="green"/><Summary icon={AlertTriangle} value={findings.length} label="Open findings" tone="orange"/></section><section className="dashboard-grid report-grid"><article className="panel"><div className="policy-toolbar"><div><h2>Cloud coverage</h2><p>Current inventory and findings by provider</p></div></div><div className="report-provider-list">{providers.map(item=><div key={item.provider}><strong>{item.provider.toUpperCase()}</strong><span>{item.resources} resources</span><em>{item.findings} findings</em></div>)}</div></article><article className="panel"><div className="policy-toolbar"><div><h2>Severity breakdown</h2><p>Failed controls requiring attention</p></div></div><div className="severity-report">{["critical","high","medium","low"].map(severity=><div key={severity}><span className={`severity ${severity}`}>{severity}</span><strong>{findings.filter(item=>item.policy?.severity===severity).length}</strong></div>)}</div></article></section><section className="panel report-findings"><div className="policy-toolbar"><div><h2>Export preview</h2><p>Evidence included in the CSV report</p></div></div>{findings.length===0?<div className="resource-state"><ShieldCheck/><strong>No non-compliant results to export</strong></div>:<div className="table-wrap"><table><thead><tr><th>Resource</th><th>Provider</th><th>Policy</th><th>Severity</th><th>Scan</th></tr></thead><tbody>{findings.map(item=><tr key={item.id}><td><strong>{item.resource?.name??`Resource #${item.resource_id}`}</strong></td><td>{item.resource?.cloud_provider.toUpperCase()??"Unknown"}</td><td>{item.policy?.name??`Policy #${item.policy_id}`}</td><td><span className={`severity ${item.policy?.severity??"high"}`}>{item.policy?.severity??"unknown"}</span></td><td>#{item.scan_id}</td></tr>)}</tbody></table></div>}</section></>}</>;
}
function Summary({icon:Icon,value,label,tone}:{icon:typeof ShieldCheck;value:number|string;label:string;tone:string}){return <div><span className={tone}><Icon/></span><strong>{value}</strong><small>{label}</small></div>}
