import { FormEvent, useCallback, useEffect, useState } from "react";
import { Boxes, Cloud, Filter, MapPin, Pencil, Plus, RefreshCw, Save, Server, X } from "lucide-react";

type Provider="aws"|"azure"|"gcp";
type Resource={id:number;name:string;resource_type:string;cloud_provider:Provider;cloud_id:string;region:string|null;status:"active"|"inactive";configuration:Record<string,unknown>;last_discovered_at:string};
const emptyForm={name:"",resource_type:"",cloud_provider:"aws" as Provider,cloud_id:"",region:"",configuration:"{}"};

export default function ResourcesPage({token,readOnly=false}:{token:string;readOnly?:boolean}){
 const [resources,setResources]=useState<Resource[]>([]),[provider,setProvider]=useState<"all"|Provider>("all");const [includeInactive,setIncludeInactive]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(""),[showCreate,setShowCreate]=useState(false),[selected,setSelected]=useState<Resource|null>(null),[form,setForm]=useState(emptyForm),[editForm,setEditForm]=useState({name:"",region:"",status:"active" as "active"|"inactive",configuration:"{}"}),[saving,setSaving]=useState(false);const api=import.meta.env.VITE_API_URL??"/api";
 const load=useCallback(async()=>{setLoading(true);setError("");const query=new URLSearchParams();if(provider!=="all")query.set("cloud_provider",provider);if(includeInactive)query.set("include_inactive","true");try{const response=await fetch(`${api}/resources?${query}`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)throw new Error(await readError(response));setResources(await response.json())}catch(reason){setError(reason instanceof Error?reason.message:"Resources could not be loaded.")}finally{setLoading(false)}},[api,includeInactive,provider,token]);useEffect(()=>{void load()},[load]);
 async function create(event:FormEvent){event.preventDefault();setSaving(true);setError("");try{const configuration=parse(form.configuration);const response=await fetch(`${api}/resources`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({...form,region:form.region||null,configuration})});if(!response.ok)throw new Error(await readError(response));setForm(emptyForm);setShowCreate(false);await load()}catch(reason){setError(message(reason,"Resource could not be created."))}finally{setSaving(false)}}
 function edit(resource:Resource){setError("");setSelected(resource);setEditForm({name:resource.name,region:resource.region??"",status:resource.status,configuration:JSON.stringify(resource.configuration,null,2)})}
 async function update(event:FormEvent){event.preventDefault();if(!selected)return;setSaving(true);setError("");try{const configuration=parse(editForm.configuration);const response=await fetch(`${api}/resources/${selected.id}`,{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({...editForm,region:editForm.region||null,configuration})});if(!response.ok)throw new Error(await readError(response));setSelected(null);await load()}catch(reason){setError(message(reason,"Resource could not be updated."))}finally{setSaving(false)}}
 return <><section className="page-heading resources-heading"><div><span className="eyebrow accent">Cloud inventory</span><h1>Resources</h1><p>{readOnly?"Review the cloud assets available for policy evaluation.":"Review and configure cloud assets available for policy evaluation."}</p></div>{!readOnly&&<button className="primary-button" onClick={()=>setShowCreate(true)}><Plus/> Add resource</button>}</section><section className="resource-summary"><Summary count={resources.length} label="Visible resources"/><>{(["aws","azure","gcp"] as Provider[]).map(item=><Summary key={item} count={resources.filter(r=>r.cloud_provider===item).length} label={item.toUpperCase()}/>)}</></section>
 <section className="panel resource-panel"><div className="resource-toolbar"><div className="provider-filters"><Filter/>{(["all","aws","azure","gcp"] as const).map(item=><button className={provider===item?"active":""} onClick={()=>setProvider(item)} key={item}>{item==="all"?"All providers":item.toUpperCase()}</button>)}</div><label className="inactive-toggle"><input type="checkbox" checked={includeInactive} onChange={e=>setIncludeInactive(e.target.checked)}/> Include inactive</label><button className="refresh-button" onClick={()=>void load()}><RefreshCw/> Refresh</button></div>{error&&<div className="resource-error">{error}</div>}{loading?<State text="Loading inventory…"/>:resources.length===0?<State text="No resources found"/>:<div className="resource-table-wrap"><table className="resource-table"><thead><tr><th>Resource</th><th>Provider</th><th>Type</th><th>Region</th><th>Status</th><th>Last discovered</th>{!readOnly&&<th>Action</th>}</tr></thead><tbody>{resources.map(resource=><tr key={resource.id}><td><div className="resource-name"><span><Server/></span><div><strong>{resource.name}</strong><small>{resource.cloud_id}</small></div></div></td><td><span className={`provider-pill ${resource.cloud_provider}`}>{resource.cloud_provider.toUpperCase()}</span></td><td>{resource.resource_type}</td><td><span className="region"><MapPin/>{resource.region??"Global"}</span></td><td><span className={`status-pill ${resource.status}`}>{resource.status}</span></td><td>{new Date(resource.last_discovered_at).toLocaleString()}</td>{!readOnly&&<td><button className="edit-resource-button" onClick={()=>edit(resource)}><Pencil/> Edit</button></td>}</tr>)}</tbody></table></div>}</section>
 {showCreate&&<Modal title="Add cloud resource" text="Create a resource that can be evaluated by policies and scans." close={()=>setShowCreate(false)}><form onSubmit={create}><div className="form-grid"><label>Resource name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Resource type<input required value={form.resource_type} onChange={e=>setForm({...form,resource_type:e.target.value})}/></label><label>Cloud provider<select value={form.cloud_provider} onChange={e=>setForm({...form,cloud_provider:e.target.value as Provider})}><option value="aws">AWS</option><option value="azure">Azure</option><option value="gcp">Google Cloud</option></select></label><label>Region<input value={form.region} onChange={e=>setForm({...form,region:e.target.value})}/></label></div><label>Cloud resource ID<input required value={form.cloud_id} onChange={e=>setForm({...form,cloud_id:e.target.value})}/></label><label>Configuration JSON<textarea required rows={6} spellCheck={false} value={form.configuration} onChange={e=>setForm({...form,configuration:e.target.value})}/></label><Actions cancel={()=>setShowCreate(false)} saving={saving} label="Add resource"/></form></Modal>}
 {selected&&<Modal title="Edit resource" text="Update the configuration, then run a verification scan." close={()=>setSelected(null)}><form onSubmit={update}><div className="form-grid"><label>Resource name<input required value={editForm.name} onChange={e=>setEditForm({...editForm,name:e.target.value})}/></label><label>Region<input value={editForm.region} onChange={e=>setEditForm({...editForm,region:e.target.value})}/></label><label>Status<select value={editForm.status} onChange={e=>setEditForm({...editForm,status:e.target.value as "active"|"inactive"})}><option value="active">Active</option><option value="inactive">Inactive</option></select></label></div><label>Configuration JSON<textarea required rows={7} spellCheck={false} value={editForm.configuration} onChange={e=>setEditForm({...editForm,configuration:e.target.value})}/></label>{error&&<div className="resource-error modal-error">{error}</div>}<Actions cancel={()=>setSelected(null)} saving={saving} label="Save changes" save/></form></Modal>}</>;
}
function Modal({title,text,close,children}:{title:string;text:string;close:()=>void;children:React.ReactNode}){return <div className="modal-backdrop"><section className="resource-modal" role="dialog" aria-modal="true"><div className="modal-heading"><div><span className="eyebrow accent">Inventory configuration</span><h2>{title}</h2><p>{text}</p></div><button type="button" className="icon-button" onClick={close}><X/></button></div>{children}</section></div>}
function Actions({cancel,saving,label,save=false}:{cancel:()=>void;saving:boolean;label:string;save?:boolean}){return <div className="modal-actions"><button type="button" onClick={cancel}>Cancel</button><button className="primary-button" disabled={saving}>{save&&<Save/>}{saving?"Saving…":label}</button></div>}
function Summary({count,label}:{count:number;label:string}){return <div><span><Cloud/></span><strong>{count}</strong><small>{label}</small></div>}
function State({text}:{text:string}){return <div className="resource-state"><Boxes/><strong>{text}</strong></div>}
function parse(value:string){try{return JSON.parse(value) as Record<string,unknown>}catch{throw new Error("Configuration must be valid JSON.")}}
function message(reason:unknown,fallback:string){return reason instanceof Error?reason.message:fallback}
async function readError(response:Response){try{const body=await response.json();return typeof body.detail==="string"?body.detail:"Please check the resource details."}catch{return "The service returned an unexpected response."}}
