import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, CalendarDays, CheckCircle2, Clock3, Cloud, History, Play, Plus, Radar, RefreshCw, Save, ShieldCheck, Siren, UserRound, X, XCircle } from "lucide-react";

type Provider="aws"|"azure"|"gcp"; type ScanStatus="pending"|"queued"|"running"|"completed"|"failed";
type Scan={id:number;cloud_provider:Provider;resource_type:string|null;job_id:string|null;status:ScanStatus;total_resources:number;compliant_count:number;non_compliant_count:number;error_message:string|null;created_at:string;started_at:string|null;completed_at:string|null};
type RemediationStatus="open"|"in_progress"|"resolved"|"risk_accepted";
type RemediationEvent={id:number;previous_status:RemediationStatus;new_status:RemediationStatus;note:string|null;created_at:string};
type Result={id:number;scan_id:number;resource_id:number;policy_id:number;compliant:boolean;details:string;remediation_status:RemediationStatus;assigned_to_user_id:number|null;due_at:string|null;remediation_note:string|null;resolved_at:string|null;remediation_events:RemediationEvent[];created_at:string};
type Resource={id:number;name:string;cloud_id:string;resource_type:string;cloud_provider:Provider}; type Policy={id:number;name:string;severity:string};
type Finding=Result&{resource?:Resource;policy?:Policy;scan?:Scan};

export default function ScansPage({token,initialTab,currentUserId,readOnly=false}:{token:string;initialTab:"scans"|"findings";currentUserId:number;readOnly?:boolean}){
  const [tab,setTab]=useState(initialTab); const [scans,setScans]=useState<Scan[]>([]); const [findings,setFindings]=useState<Finding[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [showCreate,setShowCreate]=useState(false); const [selectedFinding,setSelectedFinding]=useState<Finding|null>(null); const [remediationForm,setRemediationForm]=useState({status:"in_progress" as RemediationStatus,assignedToMe:true,dueAt:"",note:""}); const [form,setForm]=useState({cloud_provider:"aws" as Provider,resource_type:"storage_bucket"}); const [saving,setSaving]=useState(false); const apiBase=import.meta.env.VITE_API_URL??"/api"; const headers={Authorization:`Bearer ${token}`};
  useEffect(()=>setTab(initialTab),[initialTab]);

  const load=useCallback(async()=>{setError("");try{const scanResponse=await fetch(`${apiBase}/scans`,{headers});if(!scanResponse.ok)throw new Error(await readError(scanResponse));const scanData:Scan[]=await scanResponse.json();setScans(scanData);if(initialTab==="findings"||scanData.some(scan=>scan.status==="completed")){const [resourceResponse,policyResponse,remediationResponse]=await Promise.all([fetch(`${apiBase}/resources?include_inactive=true`,{headers}),fetch(`${apiBase}/policies?include_inactive=true`,{headers}),fetch(`${apiBase}/remediations`,{headers})]);if(!remediationResponse.ok)throw new Error(await readError(remediationResponse));const resources:Resource[]=resourceResponse.ok?await resourceResponse.json():[];const policies:Policy[]=policyResponse.ok?await policyResponse.json():[];const results:Result[]=await remediationResponse.json();const resourceMap=new Map(resources.map(item=>[item.id,item]));const policyMap=new Map(policies.map(item=>[item.id,item]));const scanMap=new Map(scanData.map(item=>[item.id,item]));setFindings(results.map(result=>({...result,resource:resourceMap.get(result.resource_id),policy:policyMap.get(result.policy_id),scan:scanMap.get(result.scan_id)})));}}catch(reason){setError(reason instanceof Error?reason.message:"Scan data could not be loaded.");}finally{setLoading(false);}},[apiBase,token,initialTab]);
  useEffect(()=>{setLoading(true);void load();},[load]);
  useEffect(()=>{if(!scans.some(scan=>["queued","running"].includes(scan.status)))return;const timer=window.setInterval(()=>void load(),2000);return()=>window.clearInterval(timer);},[scans,load]);

  async function createScan(event:FormEvent){event.preventDefault();setSaving(true);setError("");try{const response=await fetch(`${apiBase}/scans`,{method:"POST",headers:{...headers,"Content-Type":"application/json"},body:JSON.stringify({cloud_provider:form.cloud_provider,resource_type:form.resource_type||null})});if(!response.ok)throw new Error(await readError(response));setShowCreate(false);await load();}catch(reason){setError(reason instanceof Error?reason.message:"Scan could not be created.");}finally{setSaving(false);}}
  async function runScan(scanId:number){setError("");try{const response=await fetch(`${apiBase}/scans/${scanId}/run`,{method:"POST",headers});if(!response.ok)throw new Error(await readError(response));await load();}catch(reason){setError(reason instanceof Error?reason.message:"Scan could not be queued.");}}
  function manageFinding(item:Finding){setSelectedFinding(item);setRemediationForm({status:item.remediation_status==="open"?"in_progress":item.remediation_status,assignedToMe:item.assigned_to_user_id===currentUserId,dueAt:item.due_at?item.due_at.slice(0,10):"",note:item.remediation_note??""});}
  async function updateRemediation(event:FormEvent){event.preventDefault();if(!selectedFinding)return;setSaving(true);setError("");try{const response=await fetch(`${apiBase}/remediations/${selectedFinding.id}`,{method:"PATCH",headers:{...headers,"Content-Type":"application/json"},body:JSON.stringify({status:remediationForm.status,assigned_to_user_id:remediationForm.assignedToMe?currentUserId:null,due_at:remediationForm.dueAt?new Date(`${remediationForm.dueAt}T17:00:00Z`).toISOString():null,note:remediationForm.note||null})});if(!response.ok)throw new Error(await readError(response));setSelectedFinding(null);await load();}catch(reason){setError(reason instanceof Error?reason.message:"Remediation could not be updated.");}finally{setSaving(false);}}
  const stats=useMemo(()=>({total:scans.length,active:scans.filter(scan=>["queued","running"].includes(scan.status)).length,completed:scans.filter(scan=>scan.status==="completed").length,findings:findings.filter(item=>["open","in_progress"].includes(item.remediation_status)).length}),[scans,findings]);

  return <>
    <section className="page-heading"><div><span className="eyebrow accent">Background compliance</span><h1>{tab==="scans"?"Scans":"Findings"}</h1><p>{tab==="scans"?(readOnly?"Review deterministic compliance jobs processed by Celery.":"Create and monitor deterministic compliance jobs processed by Celery."):"Review stored policy failures produced by completed scans."}</p></div>{tab==="scans"&&!readOnly&&<button className="primary-button" onClick={()=>setShowCreate(true)}><Plus/> New scan</button>}</section>
    <div className="scan-tabs"><button className={tab==="scans"?"active":""} onClick={()=>setTab("scans")}><Radar/> Scans</button><button className={tab==="findings"?"active":""} onClick={()=>setTab("findings")}><Siren/> Findings <span>{stats.findings}</span></button></div>
    <section className="scan-summary"><Summary icon={Radar} value={stats.total} label="Total scans" tone="blue"/><Summary icon={Activity} value={stats.active} label="Processing" tone="cyan"/><Summary icon={CheckCircle2} value={stats.completed} label="Completed" tone="green"/><Summary icon={AlertTriangle} value={stats.findings} label="Open findings" tone="orange"/></section>
    {error&&<div className="resource-error scan-page-error">{error}</div>}
    {tab==="scans"?<section className="panel scans-workspace"><div className="policy-toolbar"><div><h2>Scan activity</h2><p>Live status from the background processing pipeline</p></div><button type="button" className="refresh-button" onClick={()=>void load()}><RefreshCw/> Refresh</button></div>{loading?<Loading label="Loading scans…"/>:scans.length===0?<Empty icon={Radar} title="No scans yet" text="Create the first compliance scan for your inventory." action={()=>setShowCreate(true)}/>:<div className="scan-table-wrap"><table className="scan-table"><thead><tr><th>Scan</th><th>Provider</th><th>Status</th><th>Resources</th><th>Compliance</th><th>Created</th><th>Action</th></tr></thead><tbody>{scans.map(scan=><tr key={scan.id}><td><strong>Scan #{scan.id}</strong><small>{scan.resource_type??"All resource types"}</small></td><td><span className={`provider-pill ${scan.cloud_provider}`}>{scan.cloud_provider.toUpperCase()}</span></td><td><ScanStatusBadge status={scan.status}/>{scan.error_message&&<small className="scan-error">{scan.error_message}</small>}</td><td>{scan.total_resources}</td><td>{scan.status==="completed"?<div className="compliance-counts"><span>{scan.compliant_count} passed</span><span>{scan.non_compliant_count} failed</span></div>:"—"}</td><td>{new Date(scan.created_at).toLocaleString()}</td><td>{["pending","failed"].includes(scan.status)?<button type="button" className="run-button" onClick={()=>void runScan(scan.id)}><Play/> Run</button>:scan.status==="completed"?<button type="button" className="text-button" onClick={()=>setTab("findings")}>View results</button>:<span className="processing-label"><RefreshCw className="spinning"/> Processing</span>}</td></tr>)}</tbody></table></div>}</section>:
    <section className="panel findings-workspace"><div className="policy-toolbar"><div><h2>Compliance findings</h2><p>Own, track, and resolve policy failures with preserved evidence</p></div><button className="refresh-button" onClick={()=>void load()}><RefreshCw/> Refresh</button></div>{loading?<Loading label="Loading findings…"/>:findings.length===0?<Empty icon={ShieldCheck} title="No findings" text="Completed scan results currently show no policy failures."/>:<div className="finding-list">{findings.map(item=><article className={`finding-card remediation-${item.remediation_status}`} key={item.id}><span className={`severity-icon ${item.policy?.severity??"high"}`}><XCircle/></span><div className="finding-main"><div><span className={`severity ${item.policy?.severity??"high"}`}>{item.policy?.severity??"unknown"}</span><span>Scan #{item.scan_id}</span><span className={`remediation-status ${item.remediation_status}`}>{item.remediation_status.replace("_"," ")}</span></div><h3>{item.policy?.name??`Policy #${item.policy_id}`}</h3><p>{item.details}</p><div className="finding-ownership"><span><UserRound/>{item.assigned_to_user_id===currentUserId?"Assigned to you":"Unassigned"}</span>{item.due_at&&<span><CalendarDays/>Due {new Date(item.due_at).toLocaleDateString()}</span>}<span><History/>{item.remediation_events.length} updates</span></div></div><div className="finding-resource"><small>Resource</small><strong>{item.resource?.name??`Resource #${item.resource_id}`}</strong><span>{item.resource?.cloud_provider.toUpperCase()} · {item.resource?.resource_type}</span><button className="manage-button" onClick={()=>manageFinding(item)}>Manage finding</button></div></article>)}</div>}</section>}
    {selectedFinding&&<div className="modal-backdrop"><section className="resource-modal remediation-modal" role="dialog" aria-modal="true" aria-labelledby="remediation-title"><div className="modal-heading"><div><span className="eyebrow accent">Remediation workflow</span><h2 id="remediation-title">Manage finding #{selectedFinding.id}</h2><p>{selectedFinding.policy?.name}</p></div><button type="button" className="icon-button" onClick={()=>setSelectedFinding(null)}><X/></button></div><form onSubmit={updateRemediation}><div className="form-grid"><label>Status<select value={remediationForm.status} onChange={event=>setRemediationForm({...remediationForm,status:event.target.value as RemediationStatus})}><option value="open">Open</option><option value="in_progress">In progress</option><option value="resolved">Resolved</option><option value="risk_accepted">Risk accepted</option></select></label><label>Due date<input type="date" value={remediationForm.dueAt} onChange={event=>setRemediationForm({...remediationForm,dueAt:event.target.value})}/></label></div><label className="assignment-toggle"><input type="checkbox" checked={remediationForm.assignedToMe} onChange={event=>setRemediationForm({...remediationForm,assignedToMe:event.target.checked})}/><span><UserRound/>Assign this finding to me</span></label><label>Remediation note<textarea rows={4} maxLength={2000} required={remediationForm.status==="risk_accepted"} value={remediationForm.note} onChange={event=>setRemediationForm({...remediationForm,note:event.target.value})} placeholder={remediationForm.status==="risk_accepted"?"Explain why this risk is being accepted":"Record progress, evidence, or the planned fix"}/></label><div className="remediation-history"><div><History/><strong>Activity history</strong></div>{selectedFinding.remediation_events.length===0?<p>No updates recorded yet.</p>:selectedFinding.remediation_events.map(item=><div className="history-event" key={item.id}><span>{item.previous_status.replace("_"," ")} → {item.new_status.replace("_"," ")}</span><time>{new Date(item.created_at).toLocaleString()}</time>{item.note&&<p>{item.note}</p>}</div>)}</div><div className="modal-actions"><button type="button" onClick={()=>setSelectedFinding(null)}>Cancel</button><button className="primary-button" disabled={saving}><Save/>{saving?"Saving…":"Save update"}</button></div></form></section></div>}
    {showCreate&&<div className="modal-backdrop"><section className="resource-modal scan-modal" role="dialog" aria-modal="true" aria-labelledby="create-scan-title"><div className="modal-heading"><div><span className="eyebrow accent">Celery workflow</span><h2 id="create-scan-title">Create compliance scan</h2><p>Create a pending scan, then explicitly queue it for background processing.</p></div><button type="button" className="icon-button" aria-label="Close create scan dialog" onClick={()=>setShowCreate(false)}><X/></button></div><form onSubmit={createScan}><label>Cloud provider<select value={form.cloud_provider} onChange={event=>setForm({...form,cloud_provider:event.target.value as Provider})}><option value="aws">AWS</option><option value="azure">Azure</option><option value="gcp">Google Cloud</option></select></label><label>Resource type<input minLength={3} value={form.resource_type} onChange={event=>setForm({...form,resource_type:event.target.value})} placeholder="Leave blank to scan every resource type"/></label><div className="scan-flow"><span><Clock3/>Pending</span><i/><span><Cloud/>Queue</span><i/><span><Activity/>Evaluate</span><i/><span><CheckCircle2/>Results</span></div><div className="modal-actions"><button type="button" onClick={()=>setShowCreate(false)}>Cancel</button><button type="submit" className="primary-button" disabled={saving}>{saving?"Creating…":"Create scan"}</button></div></form></section></div>}
  </>;
}

function Summary({icon:Icon,value,label,tone}:{icon:typeof Radar;value:number;label:string;tone:string}){return <div><span className={tone}><Icon/></span><strong>{value}</strong><small>{label}</small></div>}
function ScanStatusBadge({status}:{status:ScanStatus}){const Icon=status==="completed"?CheckCircle2:status==="failed"?XCircle:status==="pending"?Clock3:Activity;return <span className={`scan-status ${status}`}><Icon/>{status}</span>}
function Loading({label}:{label:string}){return <div className="resource-state"><RefreshCw className="spinning"/><strong>{label}</strong></div>}
function Empty({icon:Icon,title,text,action}:{icon:typeof Radar;title:string;text:string;action?:()=>void}){return <div className="resource-state"><Icon/><strong>{title}</strong><p>{text}</p>{action&&<button type="button" className="text-button" onClick={action}>Create a scan →</button>}</div>}
async function readError(response:Response){try{const body=await response.json();return typeof body.detail==="string"?body.detail:"The request could not be completed.";}catch{return "The service returned an unexpected response.";}}
